theme: jekyll-theme-slate
title: MFC
description: High-fidelity multiphase flow simulation
show_downloads: true
github:
  zip_url: https://github.com/MFlowCode/MFC/archive/master.zip
  tar_url: https://github.com/MFlowCode/MFC/tarball/master
  is_project_page: true
  repository_url: https://github.com/MFlowCode/MFC
